export const ADD_SET = 'ADD_SET';
export const CHANGE_SCORE = 'CHANGE_SCORE';
export const TOGGLE_SERVING = 'TOGGLE_SERVING';
export const ROTATE_PLAYERS = 'ROTATE_PLAYERS';
export const ADD_EVENT = 'ADD_EVENT';
export const REMOVE_EVENT = 'REMOVE_EVENT';
export const EDIT_EVENT = 'EDIT_EVENT';
export const SET_TIMESTAMP = 'SET_TIMESTAMP';
export const SET_WINNER = 'SET_WINNER';

export const SET_PLAYERS_STATUS = 'SET_PLAYERS_STATUS';
export const SET_AVAILABLE_PLAYERS = 'SET_AVAILABLE_PLAYERS';
